Repository Purukitto/pokemon-data.json, pull requests merged in 2020-10, with the labels that each got.

#10 Change structure of evolution changes
  pokedex.json
Labels: 🔍 Ready for Review

#11 Update README.md
  README.md
Labels: 🔍 Ready for Review

#12 [WIP] Add gender ratio to pokedex.json
  pokedex.json
Labels: 🚧 WIP

#14 [API Breaking]Update Items name structure
  items.json
Labels: hacktoberfest-accepted, ⚠️ API Update, ✅ Approved
